name: Build & Test

on:
  push:
  pull_request:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v17
        with:
          nix_conf: experimental-features = nix-command flakes

      - name: Install dependencies
        run: nix-env -iA nixos.gtest nixos.gcc nixos.cmake

      - name: Build project and tests
        run: |
          mkdir build && cd build
          cmake .. -DBUILD_TESTS=ON
          make -j4

      - name: Run tests
        working-directory: build/tests
        run: ctest -C Release -R
