name: Build & Test

on:
  push:
  pull_request:

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v17
      - name: Install build dependencies
        run: nix-shell
        #uses: jwlawson/actions-setup-cmake@v1.12
      - name: build
        run: |
          mkdir -p build && cd build
          cmake ..
          make -j4 emu-gb
          cd ..
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install gtest manually
        run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
      - name: Download object files from build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Build tests
        run: cd build && make -j4
      - name: Run tests for CPU
        run: |
          ./tests/registers
