name: Build & Test

on:
  push:
  pull_request:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure
        run: |
          addgroup --system nixbld
          adduser --home /home/nix --disabled-password --gecos "" --shell /bin/bash nix && \
          adduser nix nixbld

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v17
        with:
          nix_conf: experimental-features = nix-command flakes

      - name: Build project and tests
        run: nix build .#unit-tests

      - name: Run tests
        run: bash scripts/run-tests.sh
