name: Build & Test

on:
  push:
  pull_request:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure
        run: |
          addgroup --system nixbld
          adduser --home /home/nix --disabled-password --gecos "" --shell /bin/bash nix && \
          adduser nix nixbld && \
          mkdir -m 0755 /nix && chown nix /nix && \
          mkdir -p /etc/nix && echo 'sandbox = false' > /etc/nix/nix.conf

      - name: Install Nix
        uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install dependencies
        run: nix-env -i gtest gcc cmake -f '<nixpkgs>'

      - name: Build project and tests
        run: |
          mkdir build && cd build
          cmake .. -DBUILD_TESTS=ON
          make -j4

      - name: Run tests
        working-directory: build/tests
        run: ctest -C Release -R
