name: Build & Test

on:
  push:
  pull_request:

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v17
        with:
          nix_conf: experimental-features = nix-command flakes

      - name: Build project and tests
        run: nix build .#unit-tests

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: result

  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download buils artifacts
        uses: actions/download-artifact@v3
        with:
          name: result
          path: result

      - name: DEBUG
        run: |
          tree
          tree result
      - name: Run tests for CPU
        run: |
          sudo ./result/test_registers
